/**
 * Generates the Twemoji subset the UI needs.
 *
 * FMHY renders its emoji as Twemoji SVGs rather than text, which is why system
 * emoji (Apple's glossy set on macOS, Segoe's on Windows) look wrong beside it.
 * Emitting the same graphics makes the app match on every platform instead of
 * inheriting whatever the OS ships.
 *
 * Source: @iconify-json/twemoji (Twemoji, CC-BY 4.0).
 * Run with: node scripts/gen-emoji.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const NAMES = [
  // sidebar — wiki
  'name-badge', 'robot', 'television', 'musical-note', 'video-game', 'green-book',
  'floppy-disk', 'cyclone', 'brain', 'mobile-phone', 'penguin',
  'globe-showing-asia-australia', 'file-folder',
  // sidebar — tools
  'laptop', 'card-file-box', 'paperclip', 'left-speech-bubble', 'memo',
  'alien-monster', 'camera', 'videocassette', 'speaker-high-volume', 'red-apple',
  'man-technologist',
  // sidebar — top and more
  'books', 'newspaper', 'light-bulb', 'no-one-under-eighteen', 'warning',
  'wastebasket', 'package',
  // content markers and app entries
  'star', 'globe-with-meridians', 'repeat-button', 'sparkles', 'information',
  'house', 'magnifying-glass-tilted-left', 'four-oclock', 'down-arrow', 'gear',
  // top navigation
  'bookmark-tabs', 'open-book', 'seedling',
  // ecosystem menu
  'red-question-mark', 'bookmark', 'check-mark-button', 'rocket',
  'magnifying-glass-tilted-right', 'smiling-face-with-halo', 'house-with-garden',
  'framed-picture', 'blue-heart',
]

const iconsPath = fileURLToPath(
  new URL('../node_modules/@iconify-json/twemoji/icons.json', import.meta.url),
)
const data = JSON.parse(readFileSync(iconsPath, 'utf8'))

const width = data.width ?? 36
const height = data.height ?? 36

const entries = []
const missing = []

for (const name of NAMES) {
  const icon = data.icons[name]
  if (!icon) {
    missing.push(name)
    continue
  }
  const w = icon.width ?? width
  const h = icon.height ?? height
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">${icon.body}</svg>`
  // Encode conservatively: the result is embedded in a CSS url("...") value.
  const encoded = encodeURIComponent(svg)
    .replace(/'/g, '%27')
    .replace(/\(/g, '%28')
    .replace(/\)/g, '%29')
  entries.push(`  '${name}': '${encoded}',`)
}

if (missing.length) {
  console.error('missing icons:', missing.join(', '))
  process.exitCode = 1
}

const out = `// GENERATED by scripts/gen-emoji.mjs — do not edit.
//
// Twemoji subset (https://github.com/jdecked/twemoji), CC-BY 4.0.
// Rendered as images so emoji look identical on macOS, Windows and Linux, and
// match FMHY's own site rather than the host platform's emoji font.

export type EmojiName =
${entries.map((e) => `  | ${e.trim().split(':')[0]}`).join('\n')}

const SOURCES: Record<EmojiName, string> = {
${entries.join('\n')}
}

/** A \`url()\` value for the given emoji, ready for background-image. */
export function emojiUrl(name: EmojiName): string {
  return \`url("data:image/svg+xml,\${SOURCES[name]}")\`
}
`

const outPath = fileURLToPath(new URL('../src/ui/components/emoji.generated.ts', import.meta.url))
writeFileSync(outPath, out)
console.log(`wrote ${entries.length} icons -> src/ui/components/emoji.generated.ts`)
console.log(`size: ${(out.length / 1024).toFixed(1)} KB`)
